[global]
   workgroup = WORKGROUP
   server string = Maintenance Samba Server
   security = user
   map to guest = Bad User
   log file = /var/log/samba/%m.log
   max log size = 50
   dns proxy = no
   create mask = 0775
   directory mask = 0775

[Melderlisten]
   comment = Excel-Tabellen der Kunden-Objekte
   path = /samba_shares/Melderlisten
   writable = yes
   guest ok = yes
   read only = no
   force user = root

[Protokolle]
   comment = Aktuelle ausgefüllte Protokolle (PDF)
   path = /samba_shares/Protokolle
   writable = yes
   guest ok = yes
   read only = no
   force user = root

[Archiv]
   comment = Versionisiertes Archiv der Protokolle (Vertragsnummer/Jahr/Halbjahr/)
   path = /samba_shares/Archiv
   writable = yes
   guest ok = yes
   read only = no
   force user = root
